### PR TITLE
Replace "null" to empty string

### PR DESCRIPTION
**Pull request by tykarol**
On some pages the meta attributes like og:image, author or date have "null" (string) value so this should be replaced with null or empty string.

### CODE REVIEW

**Comment by ageitgey** [comment]
Would it be possible to add a test case that covers this?

**Comment by tykarol** [comment]
@ageitgey can you merge this? or there is any contraindications?

**Comment by ageitgey** [comment]
done

**Comment by tykarol** [comment]
Can you rebuild scripts and update version in git/npm yet? Thanks

**Pull request merged**
